/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
// Credentials are read from environment variables — never hardcoded.
export const projectId = (import.meta.env.VITE_SUPABASE_URL as string)
  ?.split("//")[1]?.split(".")[0] ?? "";
export const publicAnonKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) ?? "";
